spring:
  application:
    name: plugin-loader
plugin:
  path: C:\develop\x-project\base-framework\demo\plugin-demo\target
  scan: true
  context-path: /loader
logging:
  level:
    root: debug
server:
  servlet:
    context-path: /loader